apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    environment: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector: 
        storage: "true"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: pvc-grafana
      containers:
      - image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana-http
        readinessProbe:
          httpGet:
            path: /api/health
            port: grafana-http
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
          readOnly: false
      serviceAccountName: grafana   
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-svc
  labels:
    environment: infra
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 8080
      targetPort: grafana-http