apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: infra
spec:
  hard:
    requests.cpu: "1200m"  
    limits.cpu: "2000m"
    requests.storage: "40Gi"

# kubectl describe resourcequota/resource-quota -n infra