kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-loki
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: loki-volume
  volumeName: loki-pv-5gi