apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim-auto
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path