apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: infra
  labels:
    environment: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
        environment: infra
    spec:
      nodeSelector: 
        storage: "true"
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
            claimName: pvc-prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      initContainers:
        # allow access to PV for any user, prom runs not as a root
        - name: prometheus-data-permission-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: prometheus-storage-volume
              mountPath: /data
# kubectl port-forward pod/prometheus-deployment-5f7687766d-bl4m9 8080:9090 -n monitoring
# https://devopscube.com/setup-prometheus-monitoring-on-kubernetes/
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: prometheus-svc
  labels:
    environment: infra
spec:
  type: ClusterIP
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090

# http://prometheus-svc.monitoring.svc.cluster.local