kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometheus
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: prom-volume
  volumeName: prometheus-pv-5gi