apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-5gi
spec:
  storageClassName: grafana-volume
  capacity:
   storage: 5Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - "true"