apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv-5gi
spec:
  storageClassName: loki-volume
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/loki-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - "true"