apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-10gi
spec:
  storageClassName: db-volume
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/pg-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - "true"