apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-5gi
spec:
  storageClassName: prom-volume
  capacity:
   storage: 5Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/prom-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: storage
              operator: In
              values:
                - "true"