apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-10gi
spec:
  capacity:
   storage: 10Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  storageClassName: local
  # Bind to specific pvc
  claimRef:
    name: registry-claim-local
    namespace: infra
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - v1536572.hosted-by-vdsina.ru # create necessary directory here
